INSERT INTO guest(name,last_name,created_by)
    VALUES ('Alejandra','Hernandez',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Eduardo','Uc',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Fabiola','Suarez Tec',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Martin','Cruz',1);
 INSERT INTO guest(name,last_name,created_by)
    VALUES ('Julio','Cordoba',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Alberto','May',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Jhoni','Tec',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Jose','Cruz',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Maria','Torres',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Yareli','Sanchez',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Isabel','Uc',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Luis','Martinez',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Juan','Perez',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Natali','Hernandez',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Abril','Romero',1);