INSERT INTO guest(name,last_name,created_by)
    VALUES ('Alejandra','Hernandez',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Eduardo','Uc',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Fabiola','Suarez Tec',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Martin','Cruz',1);
 INSERT INTO guest(name,last_name,created_by)
    VALUES ('Julio','Cordoba',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Alberto','May',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Jhoni','Tec',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Jose','Cruz',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Maria','Torres',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Yareli','Sanchez',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Isabel','Uc',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Luis','Martinez',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Juan','Perez',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Natali','Hernandez',1);
INSERT INTO guest(name,last_name,created_by)
    VALUES ('Abril','Romero',1);


Agregar Eventos

INSERT INTO event_uc(name,organizer_id,observations,created_by)
    VALUES ('Taller SQL',1,'Taller para aprender SQL',1);
INSERT INTO event_uc(name,organizer_id,observations,created_by)
    VALUES ('Taller SAP',2,'Taller para aprender SAP',2);
INSERT INTO event_uc(name,organizer_id,observations,created_by)
    VALUES ('Taller QNAmAKER',3,'Taller para aprender QNAMaker',3);
INSERT INTO event_uc(name,organizer_id,observations,created_by)
    VALUES ('Taller Macrosoft',4,'Taller para aprender Macrosoft',4);
INSERT INTO event_uc(name,organizer_id,observations,created_by)
    VALUES ('Taller Xamp',5,'Taller para aprender Xamp',5);
INSERT INTO event_uc(name,organizer_id,observations,created_by)
    VALUES ('Taller Oracle',6,'Taller para aprender Oracle',6);
INSERT INTO event_uc(name,organizer_id,observations,created_by)
    VALUES ('Taller Visual Studio',7,'Taller para aprender Visual',1);
INSERT INTO event_uc(name,organizer_id,observations,created_by)
    VALUES ('Taller Github',8,'Taller para aprender Github',2);


